version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
  app:
    build: chat-app
    volumes:
      - ./chat-app/dist/:/data/www/
    ports:
      - "8080:80"
  user-service:
    build: user-service
    volumes:
      - ./user-service/:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - rabbitmq
  room-service:
    build: room-service
    volumes:
      - ./room-service/:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - rabbitmq