version: '3'
services:
  app:
    build: chat-app
    volumes:
      - ./chat-app/dist/:/data/www/
    ports:
      - "8080:80"
  user-service:
    build: user-service
    volumes:
      - ./user-service/:/usr/app/
      - /usr/app/node_modules